* C++ Project Template

  A C++ Project Template. 
  Because you should concentrate on the important parts.

** Introduction
This is a minimal, blank cmake project for C++.
Making files, folders, CMakeLists.txt and all the boring stuff: done and ready to go.


** How to use 
*** Clone or fork or download
- Clone this project and use it as you wish.
  The project will appear as cloned.
  
#+begin_src Shell
git clone https://github.com/Red-Portal/project-template.git
cd project-template
#+end_src

- Fork this project and use it. If you are really lazy.
  The project will appear as forked
  
- Download and unzip the project.
  
  
*** Change the default project name
change all occurences of ~template-project~ to your project name!
Run the install script as below in order to do this automatically.
The install script will self delete upon success.

#+begin_src Shell
sudo sh ./install.sh --NAME=PROJECT_NAME
#+end_src

Windows powershell script will be added soon

*** Use it as you wish
- Add custom CMake Find modules to ~./cmake~
- Add header interfaces to ~./include/PROJECT_NAME/~
- Add source files to ~./src~
- Add documentations to ~./doc~
  

** Requirements
   1) git
   2) C++ compiler
   3) CMake
      
** How to contribute
This project is open for contribution.
Send me push requests any time you have a good idea.
Please describe reasons for additions or fixes.

** Licence

MIT License

Copyright (c) 2017 Red-Portal

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

